use v2 of cosmwasm-std
larry0x/cw-plus-plus pull request #22
Opened 2024-04-03 20:12 UTC by PFC-developer

trying start a project with 2.0 of the sdk, and this was bringing in old packages

points of interest:
- upgraded to 2.0 versions of packages
- changed version# to reflect the v2.0
- some lifetimes are now static, from 'a
- upgraded to Syn v2 (derive stuff)
- moved to properly formed bech32 addresses, as code actually validates their validity (not sure if there is my issue or a 2.0 one)

tests pass.
didn't run format (as you have very precise formatting, and didn't want to ruin it)

2024-04-08 10:28 UTC, ratik requested changes
just some redundant spaces

2024-04-08 10:28 UTC, ratik commented on packages/optional-indexes/src/unique.rs
> +    idx_map: Map< IK, UniqueRef<T>>,
```suggestion
    idx_map: Map<IK, UniqueRef<T>>,
```

2024-04-08 10:28 UTC, ratik commented on packages/item-set/src/lib.rs
> +    counter: Item< u64>,
```suggestion
    counter: Item<u64>,
```

2024-04-08 10:28 UTC, ratik commented on packages/paginate/src/lib.rs
> +    map: &Map< K, T>,
```suggestion
    map: &Map<K, T>,
```

2024-04-08 10:28 UTC, ratik commented on packages/paginate/src/lib.rs
> +    map: &Map< K, T>,
```suggestion
    map: &Map<K, T>,
```

2024-04-08 10:28 UTC, ratik commented on packages/paginate/src/lib.rs
> +    map: &IndexedMap< K, T, I>,
```suggestion
    map: &IndexedMap<K, T, I>,
```

2024-04-08 15:57 UTC, ratik approved these changes

2024-07-17 21:31 UTC, PFC-developer commented
closing as #23 seemed to have accomplished the same thing

2024-07-17 21:31 UTC, closed without merging